name = "rest-express-app"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "rest-express-app"

[env.preview]
name = "rest-express-app-preview"

# Build configuration
[build]
command = "npm run build:cloudflare"
cwd = "."
watch_dir = "."

# Pages configuration
pages_build_output_dir = "dist/public"

# Environment variables (set via wrangler secret put or dashboard)
[vars]
NODE_ENV = "production"

# Database bindings (if using Cloudflare D1)
# [[d1_databases]]
# binding = "DB"
# database_name = "rest-express-db"
# database_id = "your-database-id"

# KV namespace bindings (if needed)
# [[kv_namespaces]]
# binding = "KV"
# id = "your-kv-namespace-id"