name = "resilience-solutions"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = "dist"

[env.production]
vars = { NODE_ENV = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "resilience-solutions-prod"
database_id = "your-d1-database-id"

[[env.production.kv_namespaces]]
binding = "KV"
id = "your-kv-namespace-id"

[env.development]
vars = { NODE_ENV = "development" }

[[env.development.d1_databases]]
binding = "DB"
database_name = "resilience-solutions-dev"
database_id = "your-d1-dev-database-id"

[[env.development.kv_namespaces]]
binding = "KV"
id = "your-dev-kv-namespace-id"

# Environment variables that will be set in Cloudflare dashboard:
# EMAILOCTOPUS_API_KEY
# EMAILOCTOPUS_MAIN_LIST_ID
# ADMIN_EMAIL
# FROM_EMAIL
# DATABASE_URL (if using external PostgreSQL instead of D1)
# OPENAI_API_KEY